/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankapp;

import javax.swing.JOptionPane;

/**
 *
 * @author TheDreamComesTrue
 */
public class AddAccountMenu extends javax.swing.JDialog {
    private Bank bank;
    Customer customer;
    /**
     * Creates new form AddAccountMenu
     */
    public AddAccountMenu(java.awt.Frame parent, boolean modal, Bank bank) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        this.bank = bank;
        customer = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        surnameLabel = new javax.swing.JLabel();
        surnameField = new javax.swing.JTextField();
        idLabel = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        depositLabel = new javax.swing.JLabel();
        depositField = new javax.swing.JTextField();
        typeLabel = new javax.swing.JLabel();
        typeField = new javax.swing.JComboBox<>();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Account Menu");
        getContentPane().setLayout(new java.awt.GridLayout(6, 2, 5, 5));

        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLabel.setText("Name");
        getContentPane().add(nameLabel);

        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });
        getContentPane().add(nameField);

        surnameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        surnameLabel.setText("Surname");
        getContentPane().add(surnameLabel);
        getContentPane().add(surnameField);

        idLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        idLabel.setText("Identification Number");
        getContentPane().add(idLabel);
        getContentPane().add(idField);

        depositLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        depositLabel.setText("Initial Deposit");
        getContentPane().add(depositLabel);
        getContentPane().add(depositField);

        typeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        typeLabel.setText("Account Type");
        getContentPane().add(typeLabel);

        typeField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Checking", "Saving" }));
        typeField.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        typeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeFieldActionPerformed(evt);
            }
        });
        getContentPane().add(typeField);

        okButton.setText("Proceed");
        okButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        getContentPane().add(okButton);

        cancelButton.setText("Cancel");
        cancelButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cancelButton);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void typeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeFieldActionPerformed

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        StringBuilder warnings = new StringBuilder();
        String name = "";
        String surname = "";
        String id = "";
        String deposit = "";
        double amount = 0;
        
        
        

        //verify name field
        if(nameField.getText().isEmpty()){
           warnings.append("Name must not be empty. \n");
        }
        else{
            name = nameField.getText();
        }
        //verify surname field
             if(surnameField.getText().isEmpty()){
           warnings.append("Surname must not be empty. \n");
        }
             else{
                 surname = surnameField.getText();
             }
        //verify id
             if(idField.getText().isEmpty()){
            warnings.append("ID must not be empty. \n");
        }
             if(!idField.getText().matches("(\\d+-?)+")){
                warnings.append("ID must be a number \n");
             }
             else{
                 id = idField.getText().replace("-", "");
             }
        //verify initial deposit
        if(depositField.getText().isEmpty()){
            warnings.append("Initial deposit must be entered.");
        }
        else{
            try{
            amount = Bank.round(Double.parseDouble(depositField.getText()),2);
        }
            catch(NumberFormatException ex){
                warnings.append("Initial deposit must be a number.");
            }
        }
        
        if(warnings.length()>0){
            JOptionPane.showMessageDialog(this, warnings.toString(),"Input Warnings", JOptionPane.WARNING_MESSAGE);
        }
        else{
            Account account = null;
            if(typeField.getSelectedItem().toString() == "Checking"){
                if(amount >= 100){
                    account = new Checking(amount);
                }
                else{
                    warnings.append("Initial deposit must be at least 100 zloty for a checking account");
                }
                
            }
            else if(typeField.getSelectedItem().toString() == "Savings"){
                 if(amount >= 50){
                    account = new Savings(amount);
                }
                else{
                    warnings.append("Initialdeposit must be at least 50 zloty for a savings account");
                }
                
            }
            if(account !=null){
               
            customer = new Customer(name, surname, id, account);
            bank.addCustomer(customer);
            this.dispose();
            }else{
                JOptionPane.showMessageDialog(this, warnings.toString(),"Input Warnings", JOptionPane.WARNING_MESSAGE);
            }
            
        }
    
        //create an account
        
    }//GEN-LAST:event_okButtonActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField depositField;
    private javax.swing.JLabel depositLabel;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton okButton;
    private javax.swing.JTextField surnameField;
    private javax.swing.JLabel surnameLabel;
    private javax.swing.JComboBox<String> typeField;
    private javax.swing.JLabel typeLabel;
    // End of variables declaration//GEN-END:variables
Customer getCustomer(){
return customer;
}
}